#!/bin/sh
# Regenerates docs/15_cli_reference.md from the command tree's own help.
#
# Written rather than hand-maintained for the reason every generated file is:
# a reference page listing flags is wrong the day somebody adds one, and nobody
# notices until they follow it. This asks the binary.
#
# Run with --check to verify the committed page is current instead of writing
# it. CI uses that, so adding a flag without regenerating fails the build.
#
# Usage:
#   ./scripts/clidocs.sh            # write docs/15_cli_reference.md
#   ./scripts/clidocs.sh --check    # fail if it is out of date
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
out="$root/docs/15_cli_reference.md"
check=0
[ "${1:-}" = "--check" ] && check=1

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
target="$work/15_cli_reference.md"
bin="$work/doenerstag"

# Built here rather than using whatever is on PATH: the page has to describe
# this checkout, and a stale binary on PATH is exactly how a reference page
# starts lying. The version is stamped as 0.0.0-dev because it is irrelevant to
# the flags and would otherwise make the file churn on every commit.
( cd "$root" && go build -o "$bin" ./cmd/doenerstag )

# help prints one command's help inside a fenced block.
#
# COLUMNS is fixed so that the wrapping does not depend on the terminal the
# generator happened to run in, which would make the file differ between a
# developer's machine and CI for no reason anybody could see.
help() {
    printf '```\n'
    COLUMNS=100 "$bin" "$@" --help 2>&1
    printf '```\n\n'
}

{
    cat <<'HEADER'
# 15 Command line reference

Every verb, every subcommand and every flag, as the binary itself reports them.

Generated by `scripts/clidocs.sh` from the command tree. Do not edit by hand:
run the script instead, which CI checks. What the flags *mean*, and the
reasoning behind the ones whose behaviour is not obvious from a line of help
text, is in [09_configuration.md](09_configuration.md).

Three rules hold across the whole tree and are not repeated per command:

- **A secret is never accepted on the command line.** `--database-password`,
  `--database-root-password`, `--database-admin-password`, `--root-password`,
  `--jwt-secret` and `--mail-password` are read from the configuration file, the
  environment or an interactive prompt. Passing one as an argument is a fatal
  error, because command lines are visible in the process list and end up in
  shell history.
- **Every verb inherits the global flags**, so `-c` names the configuration file
  and `-L` the log destination everywhere.
- **A verb that needs a subcommand and is given none prints its help and exits
  non-zero**, so a script notices.

HEADER

    printf '## doenerstag\n\n'
    help

    # The subcommand-bearing verbs are listed explicitly rather than discovered,
    # so that the order of the page is a decision rather than an accident of
    # cobra's sorting.
    for verb in server install update cleanup version; do
        printf '## doenerstag %s\n\n' "$verb"
        help "$verb"
    done

    printf '## doenerstag user\n\n'
    help user
    for sub in list add delete password; do
        printf '### doenerstag user %s\n\n' "$sub"
        help user "$sub"
    done

    printf '## doenerstag restaurant\n\n'
    help restaurant
    for sub in list delete export import; do
        printf '### doenerstag restaurant %s\n\n' "$sub"
        help restaurant "$sub"
    done

    printf '## doenerstag order\n\n'
    help order
    for sub in list delete; do
        printf '### doenerstag order %s\n\n' "$sub"
        help order "$sub"
    done
} > "$target"

if [ "$check" -eq 1 ]; then
    if [ ! -f "$out" ]; then
        echo "docs/15_cli_reference.md is missing; run ./scripts/clidocs.sh" >&2
        exit 1
    fi
    if ! diff -q "$out" "$target" >/dev/null 2>&1; then
        echo "docs/15_cli_reference.md is out of date; run ./scripts/clidocs.sh" >&2
        diff -u "$out" "$target" | head -40 >&2
        exit 1
    fi
    echo "docs/15_cli_reference.md is current"
    exit 0
fi

mv "$target" "$out"
echo "wrote $out"
