#!/bin/sh
# Regenerates THIRD_PARTY_LICENSES.
#
# The obligation, from docs/08_technologies.md: everything distributed with the
# application travels with its licence text. That is the Go modules compiled
# into the binary and the Swagger UI files copied into static/. Build and test
# tools are not distributed and are not listed -- golangci-lint is GPL and
# axe-core is MPL, and neither places any obligation on what ships, because
# neither ships.
#
# Run with --check to verify the committed file is current instead of writing
# it. CI uses that, so adding a dependency without its licence fails the build.
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
out="$root/THIRD_PARTY_LICENSES"
check=0
[ "${1:-}" = "--check" ] && check=1

if ! command -v go-licenses >/dev/null 2>&1; then
    echo "go-licenses is not installed:" >&2
    echo "  go install github.com/google/go-licenses@latest" >&2
    exit 1
fi

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
target="$work/THIRD_PARTY_LICENSES"

{
    cat <<'HEADER'
THIRD-PARTY LICENCES
====================

doenerstag itself is licensed under the BSD 3-Clause License; see LICENSE.

This file reproduces the licence of everything distributed with it: the Go
modules compiled into the binary, and the Swagger UI files copied into static/.
Build and test tools are not listed, because they are executed rather than
distributed and place no obligation on the result.

Generated by scripts/licenses.sh. Do not edit by hand.

HEADER
} > "$target"

# --- the Go modules in the binary -------------------------------------------
#
# The embedstatic tag is what a release is built with, so it is what the
# dependency set is read from. Without it the report would miss nothing today,
# but a dependency behind that tag would be invisible.
echo "collecting Go module licences" >&2
saved="$work/go"
go-licenses save ./cmd/doenerstag \
    --save_path "$saved" \
    --force \
    >/dev/null 2>"$work/go-licenses.log" || {
        echo "go-licenses failed:" >&2
        cat "$work/go-licenses.log" >&2
        exit 1
    }

{
    echo "================================================================"
    echo "Go modules"
    echo "================================================================"
    echo
} >> "$target"

# Sorted, so the file does not churn between machines.
find "$saved" -type f \( -name 'LICENSE*' -o -name 'COPYING*' -o -name 'NOTICE*' \) \
    | LC_ALL=C sort \
    | while read -r file; do
        module=$(dirname "${file#"$saved"/}")
        {
            echo "----------------------------------------------------------------"
            echo "$module"
            echo "----------------------------------------------------------------"
            echo
            cat "$file"
            echo
        } >> "$target"
    done

# --- the frontend files that ship -------------------------------------------
#
# Only what lands in static/. Tailwind produces the stylesheet and never ships
# itself; Swagger UI's own files are copied in whole and do.
{
    echo "================================================================"
    echo "Frontend"
    echo "================================================================"
    echo
    echo "----------------------------------------------------------------"
    echo "tailwindcss -- the generated stylesheet in static/css"
    echo "----------------------------------------------------------------"
    echo
} >> "$target"

for name in tailwindcss swagger-ui-dist; do
    dir="$root/frontend/node_modules/$name"
    if [ ! -d "$dir" ]; then
        # Resolution walks up, so the toolchain may live outside the tree.
        dir="$root/../node_modules/$name"
    fi
    if [ "$name" = "swagger-ui-dist" ]; then
        {
            echo "----------------------------------------------------------------"
            echo "swagger-ui-dist -- the files copied into static/swagger"
            echo "----------------------------------------------------------------"
            echo
        } >> "$target"
    fi
    licence=$(find "$dir" -maxdepth 1 -iname 'LICENSE*' -o -maxdepth 1 -iname 'NOTICE*' 2>/dev/null | LC_ALL=C sort | head -1)
    if [ -n "$licence" ] && [ -f "$licence" ]; then
        cat "$licence" >> "$target"
        echo >> "$target"
    else
        echo "no licence file found for $name; install the frontend dependencies" >&2
        exit 1
    fi
done

if [ "$check" -eq 1 ]; then
    if [ ! -f "$out" ]; then
        echo "THIRD_PARTY_LICENSES is missing; run make licenses" >&2
        exit 1
    fi
    if ! diff -q "$out" "$target" >/dev/null 2>&1; then
        echo "THIRD_PARTY_LICENSES is out of date; run make licenses" >&2
        diff -u "$out" "$target" | head -40 >&2
        exit 1
    fi
    echo "THIRD_PARTY_LICENSES is current"
    exit 0
fi

mv "$target" "$out"
echo "wrote $out"
